# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-03 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0003_remove_comment_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='channel_id',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
    ]
